### ISSUE TITLE
Cloud-aws support for eu-london-2

### ISSUE THREAD

**Issue by nicpalmer** [nicpalmer/elasticsearch#1]
When I define cloud.aws.region in my elasticsearch.yml file - Elasticsearch fails to start. 

```
[2016-12-21 10:48:34,342][DEBUG][http.netty               ] [Hydro-Man] using max_chunk_size[8kb], max_header_size[8kb], max_initial_line_length[4kb], max_content_length[100mb], receive_predictor[512kb->512kb], pipelining[true], pipelining_max_events[10000]
[2016-12-21 10:48:34,370][DEBUG][indices.recovery         ] [Hydro-Man] using max_bytes_per_sec[40mb], concurrent_streams [3], file_chunk_size [512kb], translog_size [512kb], translog_ops [1000], and compress [true]
[2016-12-21 10:48:34,378][DEBUG][indices.store            ] [Hydro-Man] using indices.store.throttle.type [NONE], with index.store.throttle.max_bytes_per_sec [10gb]
[2016-12-21 10:48:34,379][DEBUG][indices.memory           ] [Hydro-Man] using indexing buffer size [100.7mb], with indices.memory.min_shard_index_buffer_size [4mb], indices.memory.max_shard_index_buffer_size [512mb], indices.memory.shard_inactive_time [5m], indices.memory.interval [30s]
[2016-12-21 10:48:34,385][DEBUG][indices.cache.query      ] [Hydro-Man] using [node] query cache with size [10%], actual_size [100.7mb], max filter count [1000]
[2016-12-21 10:48:34,393][DEBUG][indices.fielddata.cache  ] [Hydro-Man] using size [-1] [-1b]
Exception in thread "main" java.lang.IllegalArgumentException: No automatic endpoint could be derived from region [eu-west-2]
	at org.elasticsearch.cloud.aws.AwsEc2ServiceImpl.client(AwsEc2ServiceImpl.java:198)
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.<init>(AwsEc2UnicastHostsProvider.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```
I believe that this is due to 
`plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/AwsEc2ServiceImpl.java`

missing eu-west-2 as an available region. 

I have a PR prepped that I believe will fix this, however I want to do a little more testing first. 

```            
    case "eu-west":
                case "eu-west-1":
                    endpoint = "ec2.eu-west-1.amazonaws.com";
                    break;
                case "eu-west-2":
                    endpoint = "ec2.eu-west-2.amazonaws.com";
                    break;
                case "eu-central":
                case "eu-central-1":
                    endpoint = "ec2.eu-central-1.amazonaws.com";
                    break;
```

**Comment by nicpalmer** [comment]
Closing - merged with elastic/elasticsearch main branch now.
